# Generated by Django 6.0 on 2025-12-21 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Номер рейса состоит из кода компании и четырех цифр, например, CF1234', validators=[django.core.validators.RegexValidator('CF[0-9]{4}')], verbose_name='Номер рейса')),
                ('departure_dt_plan', models.DateTimeField(verbose_name='Планируемое время вылета')),
                ('departure_dt_fact', models.DateTimeField(verbose_name='Фактическое время вылета')),
                ('arrival_dt_plan', models.DateTimeField(verbose_name='Планируемое время прилета')),
                ('arrival_dt_fact', models.DateTimeField(verbose_name='Фактическое время прилета')),
                ('time_of_delay', models.DurationField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, help_text='Введите причину задержки вылета, прилета рейса или иные комментарии', null=True, verbose_name='Комментарий к рейсу')),
            ],
        ),
    ]
