# Generated by Django 5.2.7 on 2025-12-18 14:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя пассажира', max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(help_text='Фамилия пассажира', max_length=50, verbose_name='Фамилия')),
                ('booking_reference', models.CharField(help_text='Код бронирования состоит из 8 символов (латинские буквы и цифры)', unique=True, validators=[django.core.validators.RegexValidator('[A-Za-Z0-9]{8}')], verbose_name='Код бронирования')),
                ('status', models.CharField(choices=[('in_progress', 'На рассмотрении'), ('completed', 'Рассмотрена')], default='На рассмотрении', verbose_name='Статус')),
                ('email', models.EmailField(max_length=254)),
                ('claim', models.TextField()),
                ('attachment', models.FileField(blank=True, default=None, help_text='Приложение должно быть одним файлом', null=True, upload_to='claim_attachment/%Y/%m/%d', verbose_name='Приложение')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='employee.flight')),
            ],
        ),
    ]
