# Generated by Django 6.0 on 2025-12-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_created_alter_claim_booking_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления претензии'),
        ),
    ]
