# Generated by Django 6.0 on 2025-12-19 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='booking_reference',
            field=models.CharField(help_text='Код бронирования состоит из 8 символов (латинские буквы и цифры)', unique=True, validators=[django.core.validators.RegexValidator('[A-Z0-9]{8}')], verbose_name='Код бронирования'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='name',
            field=models.CharField(help_text='Имя пассажира как в загранпаспорте', max_length=25, validators=[django.core.validators.RegexValidator('[A-Z]+')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='surname',
            field=models.CharField(help_text='Фамилия пассажира как в загранпаспорте', max_length=50, validators=[django.core.validators.RegexValidator('[A-Z]+')], verbose_name='Фамилия'),
        ),
    ]
