# Generated by Django 5.2.7 on 2025-12-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time_fact',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time_plan',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_time_fact',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_time_plan',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_dt_fact',
            field=models.DateTimeField(default='2025-12-18 18:00:00', verbose_name='Фактическое время прилета'),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_dt_plan',
            field=models.DateTimeField(default='2025-12-18 18:00:00', verbose_name='Планируемое время прилета'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_dt_fact',
            field=models.DateTimeField(default='2025-12-18 18:00:00', verbose_name='Фактическое время вылета'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_dt_plan',
            field=models.DateTimeField(default='2025-12-18 18:00:00', verbose_name='Планируемое время вылета'),
        ),
    ]
