# Generated by Django 6.0 on 2025-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_flight_arrival_time_fact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='msc_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
