# Generated by Django 6.0 on 2025-12-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_flight_msc_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='msc_time',
            new_name='time_of_delay',
        ),
    ]
