# Generated by Django 6.0 on 2025-12-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_msc_time_flight_time_of_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='time_of_delay',
            field=models.CharField(blank=True, null=True),
        ),
    ]
