# Generated by Django 6.0 on 2025-12-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_flight_time_of_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_dt_fact',
            field=models.DateTimeField(verbose_name='Фактическое время прилета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_dt_plan',
            field=models.DateTimeField(verbose_name='Планируемое время прилета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_dt_fact',
            field=models.DateTimeField(verbose_name='Фактическое время вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_dt_plan',
            field=models.DateTimeField(verbose_name='Планируемое время вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='time_of_delay',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
