# Generated by Django 6.0 on 2025-12-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claim_flight_number'),
        ('employee', '0006_alter_flight_arrival_dt_fact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
